// src/components/RecordingStudio/UpdateRecordingStudioDialogComponent.jsx
import React, { useState, useEffect } from 'react';
import { getRecordingStudio, updateRecordingStudio } from '../../services/RecordingStudioService';

const UpdateRecordingStudioDialogComponent = ({ recordingStudioId, onClose }) => {
  const [studioName, setStudioName] = useState('');
  const [location, setLocation] = useState('');
  const [numberOfEmployees, setNumberOfEmployees] = useState('');
  const [artists, setArtists] = useState('');

  const [errors, setErrors] = useState({
    studioName: '',
    location: '',
    numberOfEmployees: ''
  });

  useEffect(() => {
    
    if(recordingStudioId){
        getRecordingStudio(recordingStudioId).then((response) => {
            setStudioName(response.data.studioName);
            setLocation(response.data.location);
            setNumberOfEmployees(response.data.numberOfEmployees);
            setArtists(response.data.artists);
        }).catch(error => {
            console.error(error);
        })
    }

  }, [recordingStudioId]);

  function saveRecordingStudio(e) {
    e.preventDefault();

    if (validateForm()) {
      const updatedRecordingStudio = {
        id: recordingStudioId,
        studioName,
        location,
        numberOfEmployees,
        artists
      };
      console.log(updatedRecordingStudio);
      
      updateRecordingStudio(recordingStudioId, updatedRecordingStudio)
        .then((response) => {
          console.log(response.data);
          onClose();
        })
        .catch((error) => {
          console.error(error);
        });
    }
  }

  function validateForm() {
    let valid = true;
    const errorsCopy = { ...errors };

    if (!studioName.trim()) {
      errorsCopy.studioName = 'Studio Name is required';
      valid = false;
    } else {
      errorsCopy.studioName = '';
    }

    if (!location.trim()) {
      errorsCopy.location = 'Location is required';
      valid = false;
    } else {
      errorsCopy.location = '';
    }

    if (!numberOfEmployees) {
      errorsCopy.numberOfEmployees = 'Number of employees is required';
      valid = false;
    } else {
      errorsCopy.numberOfEmployees = '';
    }

    setErrors(errorsCopy);

    return valid;
  }

  return (
    <div className="modal" style={{ display: 'block' }}>
      <div className="modal-dialog">
        <div className="modal-content">
          <div className="modal-header text-center">
            <h5 className="modal-title">Update Recording Studio</h5>
          </div>
          <div className="modal-body">
            <form onSubmit={saveRecordingStudio}>
              <div className="form-group">
                <label htmlFor="studioName">Studio Name</label>
                <input
                  type="text"
                  className="form-control"
                  id="studioName"
                  value={studioName}
                  onChange={(e) => setStudioName(e.target.value)}
                  required
                />
                {errors.studioName && <div className="text-danger">{errors.studioName}</div>}
              </div>
              <div className="form-group">
                <label htmlFor="location">Location</label>
                <input
                  type="text"
                  className="form-control"
                  id="location"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  required
                />
                {errors.location && <div className="text-danger">{errors.location}</div>}
              </div>
              <div className="form-group">
                <label htmlFor="numberOfEmployees">Number Of Employees</label>
                <input
                  type="number"
                  className="form-control"
                  id="numberOfEmployees"
                  value={numberOfEmployees}
                  onChange={(e) => setNumberOfEmployees(e.target.value)}
                  required
                />
                {errors.numberOfEmployees && (
                  <div className="text-danger">{errors.numberOfEmployees}</div>
                )}
              </div>
              <div className='text-center'>
              <button type="submit" className="btn btn-primary">
                Save
              </button>
              <button type="button" className="btn btn-secondary" onClick={onClose}>
              Close
            </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default UpdateRecordingStudioDialogComponent;

// src/app/components/recording-studio-components/update-recording-studio-dialog/update-recording-studio-dialog.component.ts
import {Component, OnInit, OnDestroy, Inject} from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { RecordingStudio } from "../../../models/recording-studio";
import { RecordingStudioService } from "../../../services/recording-studio.service";
import {animate, state, style, transition, trigger} from "@angular/animations";

@Component({
  selector: 'app-update-recording-studio-dialog',
  templateUrl: './update-recording-studio-dialog.component.html',
  styleUrls: ['./update-recording-studio-dialog.component.css'],
  animations: [
    trigger('modalAppear', [
      state('void', style({ opacity: 0})), // начальное состояние до появления
      state('*', style({ opacity: 1})), // состояние после появления
      transition('void => *', animate('300ms ease-in')), // анимация появления
      transition('* => void', animate('300ms ease-out')) // анимация исчезновения
    ])
  ]
})
export class UpdateRecordingStudioDialogComponent implements OnInit, OnDestroy {

  constructor(
    @Inject(MAT_DIALOG_DATA) public recordingStudio: RecordingStudio,
    public dialogRef: MatDialogRef<UpdateRecordingStudioDialogComponent>,
    private recordingStudioService: RecordingStudioService,
  ) {  }

  ngOnInit() {
  }

  ngOnDestroy() {
  }

  updateRecordingStudio() {
    if (this.recordingStudio.id !== undefined) {
      this.recordingStudioService.updateRecordingStudio(this.recordingStudio).subscribe(updatedRecordingStudio => {
        console.log(updatedRecordingStudio);
        this.dialogRef.close(updatedRecordingStudio);
      });
    }
  }

  cancel() {
    this.dialogRef.close();
  }
}

<div class="dialog-container" [@modalAppear]>
  <div class="dialog-content">
    <div>
      <label>Studio Name:</label>
      <input type="text" [(ngModel)]="recordingStudio.studioName" class="form-control" required>
    </div>
    <div>
      <label>Location:</label>
      <input type="text" [(ngModel)]="recordingStudio.location" class="form-control" required>
    </div>
    <div>
      <label>Number Of Employees:</label>
      <input type="number" [(ngModel)]="recordingStudio.numberOfEmployees" class="form-control" required>
    </div>
    <div style="margin-top: 10px; display: flex; justify-content: center;">
      <button (click)="updateRecordingStudio()" class="btn btn-info" style="margin-left: 10px">Save</button>
      <button (click)="cancel()" class="btn btn-danger" style="margin-left: 10px">Cancel</button>
    </div>
  </div>
</div>
