// src/app/components/recording-studio-list/recording-studio-list.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { UpdateRecordingStudioDialogComponent } from '../update-recording-studio-dialog/update-recording-studio-dialog.component';
import { RecordingStudio } from "../../models/recording-studio";
import { RecordingStudioService } from "../../services/recording-studio.service";
import { clearAllBodyScrollLocks, disableBodyScroll, enableBodyScroll } from 'body-scroll-lock';
import { CreateArtistComponent } from "../create-artist/create-artist.component";
import {ShowArtistsDialogComponent} from "../show-artists-dialog/show-artists-dialog.component";

@Component({
  selector: 'app-recording-studio-list',
  templateUrl: './recording-studio-list.component.html',
  styleUrls: ['./recording-studio-list.component.css']
})
export class RecordingStudioListComponent implements OnInit {

  recordingStudios: RecordingStudio[] = [];

  constructor(
    private recordingStudioService: RecordingStudioService,
    private dialog: MatDialog
  ) { }

  ngOnInit() {
    this.getRecordingStudios();
  }

  ngOnDestroy() {
    clearAllBodyScrollLocks();
  }

  private getRecordingStudios() {
    this.recordingStudioService.getRecordingStudiosList().subscribe(data => {
      this.recordingStudios = data;
    });
  }

  deleteRecordingStudio(id: number | undefined) {
    this.recordingStudioService.deleteRecordingStudio(id).subscribe(data => {
      console.log(data);
      this.getRecordingStudios();
    });
  }

  addArtist(recordingStudioId: number | undefined) {
    const targetElement = document.querySelector('body')!;
    disableBodyScroll(targetElement);

    const dialogRef = this.dialog.open(CreateArtistComponent, {
      width: '500px',
      data: recordingStudioId,
      disableClose: true
    });

    dialogRef.afterClosed().subscribe(() => {
      enableBodyScroll(targetElement); // Разблокировать прокрутку
    });
  }


  showArtists(recordingStudio : RecordingStudio) {

    if (recordingStudio.id !== undefined) {
      this.recordingStudioService.getArtistsList(recordingStudio.id).subscribe(data => {
        console.log('Received data:', data);

        const targetElement = document.querySelector('body')!;
        disableBodyScroll(targetElement);

        const dialogRef = this.dialog.open(ShowArtistsDialogComponent, {
          width: '500px',
          data: {
            recordingStudioName: recordingStudio.studioName,
            artists: data,
            recordingStudioId: recordingStudio.id
          },
          disableClose: true
        });

        dialogRef.afterClosed().subscribe(() => {
          enableBodyScroll(targetElement); // Разблокировать прокрутку
        });

      });
    }

  }


  openUpdateRecordingStudioDialog(recordingStudio: RecordingStudio): void {

    const targetElement = document.querySelector('body')!;
    disableBodyScroll(targetElement); // Блокировать прокрутку

    const dialogRef = this.dialog.open(UpdateRecordingStudioDialogComponent, {
      width: '500px',
      data: recordingStudio,
      disableClose: true // Запретить закрытие модального окна по клику вне его
    });

    dialogRef.afterClosed().subscribe(() => {
      enableBodyScroll(targetElement); // Разблокировать прокрутку
    });
  }

}

<h2>Recording Studios List</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Studio Name</th>
    <th>Location</th>
    <th>Number Of Employees</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <ng-container *ngFor="let recordingStudio of recordingStudios">
    <tr>
      <td>{{ recordingStudio.studioName }}</td>
      <td>{{ recordingStudio.location }}</td>
      <td>{{ recordingStudio.numberOfEmployees }}</td>
      <td>
        <button (click)="openUpdateRecordingStudioDialog(recordingStudio)" class="btn btn-info" style="margin-left: 10px">Change</button>
        <button (click)="addArtist(recordingStudio.id)" class="btn btn-info" style="margin-left: 10px">Add Artist</button>
        <button (click)="showArtists(recordingStudio)" class="btn btn-info" style="margin-left: 10px">Show Artists</button>
        <button (click)="deleteRecordingStudio(recordingStudio.id)" class="btn btn-danger" style="margin-left: 10px">Delete</button>
        <div id="div{recordingStudio.id}"></div>
      </td>
    </tr>
  </ng-container>
  </tbody>
</table>

// src/components/RecordingStudio/RecordingStudioListComponent.jsx
import React, { useEffect, useState } from 'react';
import { recordingStudioList, deleteRecordingStudio } from '../../services/RecordingStudioService';
import AddRecordingStudioDialogComponent from './AddRecordingStudioDialogComponent';
import ModalComponent from '../ModalComponent';
import UpdateRecordingStudioDialogComponent from './UpdateRecordingStudioDialogComponent';

const RecordingStudioComponent = () => {
  const [recordingStudios, setRecordingStudios] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [selectedRecordingStudioId, setSelectedRecordingStudioId] = useState(null);

  useEffect(() => {
    fetchRecordingStudios();
  }, []);

  function fetchRecordingStudios() {
    recordingStudioList()
      .then((response) => {
        setRecordingStudios(response.data);
      })
      .catch((error) => {
        console.error(error);
      });
  }

  function addRecordingStudio() {
    setShowModal(true);
  }

  function updateRecordingStudio(id) {
    setSelectedRecordingStudioId(id);
    setShowModal(true);
  }

  function delRecrodingStudio(id) {
    deleteRecordingStudio(id)
        .then((response) => {
          console.log(response.data);
          fetchRecordingStudios();
          onClose();
        })
        .catch((error) => {
          console.error(error);
        });
  }

  function closeModal() {
    setShowModal(false);
    setSelectedRecordingStudioId(null);
    fetchRecordingStudios();
  }

  return (
    <div className="container">
      <h2 className="text-center">Recording Studios List</h2>
      <button type="button" className="btn btn-primary" onClick={addRecordingStudio}>
        Add Recording Studio
      </button>

      {showModal && (
        <ModalComponent onClose={closeModal} title={selectedRecordingStudioId ? 'Edit Recording Studio' : 'Add Recording Studio'}>
          {selectedRecordingStudioId ? (
            <UpdateRecordingStudioDialogComponent recordingStudioId={selectedRecordingStudioId} onClose={closeModal} />
          ) : (
            <AddRecordingStudioDialogComponent onClose={closeModal} />
          )}
        </ModalComponent>
      )}

      <table className="table table-stripped">
        <thead>
          <tr>
            <th>Studio Name</th>
            <th>Location</th>
            <th>Number Of Employees</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {recordingStudios.map((recordingStudio) => (
            <tr key={recordingStudio.id}>
              <td>{recordingStudio.studioName}</td>
              <td>{recordingStudio.location}</td>
              <td>{recordingStudio.numberOfEmployees}</td>
              <td>
                <button className="btn btn-info"  onClick={() => updateRecordingStudio(recordingStudio.id)} >
                  Edit
                </button>
                <button className="btn btn-danger " onClick={() => delRecrodingStudio(recordingStudio.id)}>
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default RecordingStudioComponent;
